---
 - name: Working with include_tasks module
   hosts: localhost
   gather_facts: false
   tasks:
     - name: Play 1 - Task 1
       debug:
         msg: "Play 1 - Task 1"
     - import_tasks: tasks-1.yml
 - import_playbook: play2.yml
 