---
 - name: Logical Operator
   hosts: server2
   gather_facts: false
   vars:
     hello: true
     say_something: "{% if hello == true %} Hello Jinja {% else %} Goodbye Ansible {% endif %}"
   tasks:
     - debug:
         msg:
          - "{{ say_something }}"